/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoramvc;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author kokoju
 */
public class CalculadoraFrame extends javax.swing.JFrame {  // Frame que tiene nuestra cálculadora
    private CalculadoraLogic calculadoraLogic;
    private ArrayList<JButton> arregloBtns;  // Arreglo para el guardado de botones
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName());

    /**
     * Creates new form CalculadoraFrame
     */
    public CalculadoraFrame() {
        this.initComponents();
        this.arregloBtns = new ArrayList<>();  // Se inicia el arreglo
        this.addArregloBtns();  // Añade los botones al arreglo
        this.calculadoraLogic = new CalculadoraLogic(this);  // Se crea la lógica, enviándose a sí misma como referencia de cliente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBinary = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPantalla = new javax.swing.JTextArea();
        btnData = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btnPrime = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnAverage = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnMAdd = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnSpace = new javax.swing.JButton();
        btnSubNum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        btnBinary.setBackground(new java.awt.Color(0, 0, 0));
        btnBinary.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnBinary.setForeground(new java.awt.Color(255, 255, 255));
        btnBinary.setText("BINARY");
        btnBinary.setFocusable(false);

        txaPantalla.setBackground(new java.awt.Color(255, 255, 255));
        txaPantalla.setColumns(20);
        txaPantalla.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txaPantalla.setForeground(new java.awt.Color(0, 0, 0));
        txaPantalla.setRows(5);
        txaPantalla.setFocusable(false);
        jScrollPane1.setViewportView(txaPantalla);

        btnData.setBackground(new java.awt.Color(0, 0, 0));
        btnData.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnData.setForeground(new java.awt.Color(255, 255, 255));
        btnData.setText("DATA");
        btnData.setFocusable(false);
        btnData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.setFocusable(false);

        btnPrime.setBackground(new java.awt.Color(0, 0, 0));
        btnPrime.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnPrime.setForeground(new java.awt.Color(255, 255, 255));
        btnPrime.setText("PRIME");
        btnPrime.setFocusable(false);

        btn8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.setFocusable(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.setFocusable(false);

        btn4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.setFocusable(false);

        btn5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.setFocusable(false);

        btn6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.setFocusable(false);

        btn1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.setFocusable(false);

        btn2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.setFocusable(false);

        btn3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.setFocusable(false);

        btn0.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.setFocusable(false);

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setFocusable(false);

        btnDiv.setBackground(new java.awt.Color(0, 204, 255));
        btnDiv.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnDiv.setText("÷");
        btnDiv.setFocusable(false);

        btnDot.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnDot.setText(".");
        btnDot.setFocusable(false);

        btnAverage.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnAverage.setText("Average");
        btnAverage.setFocusable(false);

        btnMul.setBackground(new java.awt.Color(0, 204, 255));
        btnMul.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnMul.setText("*");
        btnMul.setToolTipText("");
        btnMul.setFocusable(false);

        btnSub.setBackground(new java.awt.Color(0, 204, 255));
        btnSub.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnSub.setText("-");
        btnSub.setFocusable(false);

        btnMAdd.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnMAdd.setText("M+");
        btnMAdd.setFocusable(false);

        btnAdd.setBackground(new java.awt.Color(0, 204, 255));
        btnAdd.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setFocusable(false);

        btnRes.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnRes.setText("=");
        btnRes.setFocusable(false);

        btnSpace.setBackground(new java.awt.Color(0, 0, 0));
        btnSpace.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnSpace.setForeground(new java.awt.Color(255, 255, 255));
        btnSpace.setText("SPACE");
        btnSpace.setFocusable(false);

        btnSubNum.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnSubNum.setText("(-)");
        btnSubNum.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(btnPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSpace, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSubNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAverage;
    private javax.swing.JButton btnBinary;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnData;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnMAdd;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnPrime;
    private javax.swing.JButton btnRes;
    private javax.swing.JButton btnSpace;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnSubNum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaPantalla;
    // End of variables declaration//GEN-END:variables

    
    public void addArregloBtns() {  // Función encargada de añadir todos los botones a un arreglo
        this.arregloBtns.add(btn0);
        this.arregloBtns.add(btn1);
        this.arregloBtns.add(btn2);
        this.arregloBtns.add(btn3);
        this.arregloBtns.add(btn4);
        this.arregloBtns.add(btn5);
        this.arregloBtns.add(btn6);
        this.arregloBtns.add(btn7);
        this.arregloBtns.add(btn8);
        this.arregloBtns.add(btn9);
        this.arregloBtns.add(btnAdd);
        this.arregloBtns.add(btnAverage);
        this.arregloBtns.add(btnBinary);
        this.arregloBtns.add(btnClear);
        this.arregloBtns.add(btnData);
        this.arregloBtns.add(btnDiv);
        this.arregloBtns.add(btnDot);
        this.arregloBtns.add(btnMAdd);
        this.arregloBtns.add(btnMul);
        this.arregloBtns.add(btnPrime);
        this.arregloBtns.add(btnRes);
        this.arregloBtns.add(btnSpace);
        this.arregloBtns.add(btnSub);
        this.arregloBtns.add(btnSubNum);
    }
    
    // Métodos
    // Getters
    public ArrayList<JButton> getArregloBtns() {
        return arregloBtns;
    }
    
    public JButton getBtn0() {
        return btn0;
    }

    public JButton getBtn1() {
        return btn1;
    }

    public JButton getBtn2() {
        return btn2;
    }

    public JButton getBtn3() {
        return btn3;
    }

    public JButton getBtn4() {
        return btn4;
    }

    public JButton getBtn5() {
        return btn5;
    }

    public JButton getBtn6() {
        return btn6;
    }

    public JButton getBtn7() {
        return btn7;
    }

    public JButton getBtn8() {
        return btn8;
    }

    public JButton getBtn9() {
        return btn9;
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public JButton getBtnAverage() {
        return btnAverage;
    }

    public JButton getBtnBinary() {
        return btnBinary;
    }

    public JButton getBtnClear() {
        return btnClear;
    }

    public JButton getBtnData() {
        return btnData;
    }

    public JButton getBtnDiv() {
        return btnDiv;
    }

    public JButton getBtnDot() {
        return btnDot;
    }

    public JButton getBtnMAdd() {
        return btnMAdd;
    }

    public JButton getBtnMul() {
        return btnMul;
    }

    public JButton getBtnPrime() {
        return btnPrime;
    }

    public JButton getBtnRes() {
        return btnRes;
    }
    
    public JButton getBtnSpace() {
        return btnSpace;
    }

    public JButton getBtnSub() {
        return btnSub;
    }
    
    public JButton getBtnSubNum() {
        return btnSubNum;
    }

    public JTextArea getTxaPantalla() {
        return txaPantalla;
    }    
}
