/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoramvc;

import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author kokoju
 */
public class MemoryFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MemoryFrame.class.getName());

    /**
     * Creates new form MemoryFrame
     */
    public MemoryFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaData = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaData1 = new javax.swing.JTextArea();
        lblMemory = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaMemory = new javax.swing.JTextArea();

        txaData.setBackground(new java.awt.Color(255, 255, 255));
        txaData.setColumns(20);
        txaData.setForeground(new java.awt.Color(0, 0, 0));
        txaData.setRows(5);
        txaData.setFocusable(false);
        jScrollPane1.setViewportView(txaData);

        txaData1.setBackground(new java.awt.Color(255, 255, 255));
        txaData1.setColumns(20);
        txaData1.setForeground(new java.awt.Color(0, 0, 0));
        txaData1.setRows(5);
        txaData1.setFocusable(false);
        jScrollPane2.setViewportView(txaData1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMemory.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblMemory.setText("MEMORY");

        txaMemory.setBackground(new java.awt.Color(255, 255, 255));
        txaMemory.setColumns(20);
        txaMemory.setForeground(new java.awt.Color(0, 0, 0));
        txaMemory.setRows(5);
        txaMemory.setFocusable(false);
        jScrollPane3.setViewportView(txaMemory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblMemory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MemoryFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMemory;
    private javax.swing.JTextArea txaData;
    private javax.swing.JTextArea txaData1;
    private javax.swing.JTextArea txaMemory;
    // End of variables declaration//GEN-END:variables

    // Getters
    public JLabel getLblMemory() {
        return lblMemory;
    }

    public JTextArea getTxaMemory() {
        return txaMemory;
    }
}
